KafkaServer {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  username="admin"
  password="admin-secret"
  user_admin="admin-secret"
  user_order="order-secret"
  user_inventory="order-secret"
  user_payment="order-secret"
  user_fulfillment="order-secret"
  user_notification="order-secret";
};
