server:
  port: 8080

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/ecommerce-realm/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://${ORDER_SERVICE_HOST:localhost}:8081
          predicates:
            - Path=/orders/**
          filters:
            - TokenRelay=

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
